name: Patch vulnerable images (Action Local Containerd)
on:
  workflow_dispatch:
jobs:
  patch:
    runs-on: ubuntu-latest
    # used for pushing patched image to GHCR
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
              {
              "debug": true,
              "experimental": true,
                  "features": {
                  "containerd-snapshotter": true
                  }
              }

      - name: Build Docker image
        run: |
          docker buildx build --load -t docker.io/local/focal:20200925 -f Dockerfile.local-test .
          docker images

      - name: Get socket path
        run: |
          url=$(docker context inspect | jq -r .[0].Endpoints.docker.Host)
          socket_path=$(echo "$url" | awk -F// '{print $2}')
          echo "$socket_path"
          echo "SOCKET=$socket_path" >> $GITHUB_ENV

        # copa action will only run if there are vulnerabilities
      - name: Run Copa action
        id: copa
        uses: project-copacetic/copa-action@v1.2.1
        with:
          image: "docker.io/local/focal:20200925"
          image-report: "report.json"
          patched-tag: "patched"
          timeout: 5m
          custom-socket: ${SOCKET}
          output: out.json

      - run: sudo cat out.json

      #   # see https://github.com/docker/login-action#usage for other registries
      # - name: Login to GHCR
      #   if: steps.copa.conclusion == 'success'
      #   id: login
      #   uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push patched image
      #   if: steps.login.conclusion == 'success'
      #   run: |
      #     # retag if needed
      #     docker tag ${{ steps.copa.outputs.patched-image }} ghcr.io/project-copacetic/copa-action/test/${{ steps.copa.outputs.patched-image }}
      #     docker push ghcr.io/project-copacetic/copa-action/test/${{ steps.copa.outputs.patched-image }}